### ISSUE TITLE
Update Wiki to use ComponentSystem instead of System

### ISSUE THREAD

**Issue by Divoolej** [jtuttle/baku#2]
Hey there, I'm loving the library so far :) However, I found an issue while following the Tutorial / Quick Guide - all of the system examples still inherit from the Baku::System, which no longer works and causes a nasty error which is impossible to track without diving into the library code (which is probably going to drive many people away from the lib).

The references to Baku::System can be found here:
- https://github.com/jtuttle/baku/wiki/Quick-Start-Guide#systems
- https://github.com/jtuttle/baku/wiki/Tutorial#create-systems

I wanted to create a PR but it seems that Github doesn't allow that for the Wiki content, so I'm creating this issue instead.

@jtuttle (mentioning for visibility :))

**Comment by jtuttle** [comment]
Thanks for catching that. Fixed them both.
